name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Lint Code
        run: echo "Pull Request flag is true ${{ env.TEST }}"
    if: github.event_name == 'pull_request'

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test Code
        run: |
          curl -X "DELETE" -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}"
